// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4detALnyw8YJ2LIaD69uj54nDM_oAHRg',
    appId: '1:701960275465:web:71c2099b4f0deb66911ad8',
    messagingSenderId: '701960275465',
    projectId: 'real-estate-app-4810a',
    authDomain: 'real-estate-app-4810a.firebaseapp.com',
    storageBucket: 'real-estate-app-4810a.firebasestorage.app',
    measurementId: 'G-BR6822J4J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBabTnGwyA7Vy3xete8INF0uItWrHmm954',
    appId: '1:701960275465:android:63dc6271e57dd2cd911ad8',
    messagingSenderId: '701960275465',
    projectId: 'real-estate-app-4810a',
    storageBucket: 'real-estate-app-4810a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADxsNX54g93dtzL97qEfa8TkVSWzm7wbA',
    appId: '1:701960275465:ios:517958f85830c2eb911ad8',
    messagingSenderId: '701960275465',
    projectId: 'real-estate-app-4810a',
    storageBucket: 'real-estate-app-4810a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADxsNX54g93dtzL97qEfa8TkVSWzm7wbA',
    appId: '1:701960275465:ios:517958f85830c2eb911ad8',
    messagingSenderId: '701960275465',
    projectId: 'real-estate-app-4810a',
    storageBucket: 'real-estate-app-4810a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4detALnyw8YJ2LIaD69uj54nDM_oAHRg',
    appId: '1:701960275465:web:e6e355771a22d701911ad8',
    messagingSenderId: '701960275465',
    projectId: 'real-estate-app-4810a',
    authDomain: 'real-estate-app-4810a.firebaseapp.com',
    storageBucket: 'real-estate-app-4810a.firebasestorage.app',
    measurementId: 'G-8QC8BEM3FF',
  );
}
